Public Class DocumentosG
    Public Local As Double
    Public TipoDoc As String
    Public Numero As Double
    Public Fecha As DateTime
    Public Estado As String
    Public Cliente As Double
    Public Rut As String
    Public Aprobado As Boolean
    Public FPago As String
    Public Bodega As Double
    Public OC As String
    Public Motivo As String
    Public TipoDocReferencia As String
    Public NumDocReferencia As Double
    Public FechaDocReferencia As Date
    Public Observaciones As String
    Public Usuario As String
    Public Vendedor As String
    Public Electronica As Boolean
    Public Ticket As Double
    Public SubTotal As Double
    Public Descuento As Double
    Public Neto As Double
    Public IVA As Double
    Public iEXE As Double
    Public iMIN As Double
    Public iBEB As Double
    Public iVIN As Double
    Public iCER As Double
    Public iLIC As Double
    Public iHAR As Double
    Public iCAR As Double
    Public iFEP As Double
    Public iTAB As Double
    Public iLOG As Double
    Public iOTRO As Double
    Public Total As Double
    Public RutTransporte As String
    Public NombreTransporte As String
    Public RutChofer As String
    Public NombreChofer As String
    Public PatenteMovil As String
    Public DTE As Boolean
    Public Firma As Byte()
    Public STATUS_DTE As Double

End Class
